#!/usr/bin/env bash
# SSH Client Config.

Host *
    PasswordAuthentication no
    IdentityFile ~/.ssh/school 
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
